# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RESTFullApi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RESTFullApi
  pod 'SwiftyJSON'


  target 'RESTFullApiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RESTFullApiUITests' do
    # Pods for testing
  end

end
